services:
  - type: web
    name: dermacare-api
    env: python
    # This is the correct syntax to force Render to use Python 3.11
    pythonVersion: "3.11"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"